kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /srv/nfs/exports
    containerPath: /files
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
