apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: fastapi-app
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      protocol: TCP
