apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: fastapi-app
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: fastapi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: fastapi-app
    spec:
      containers:
      - name: api
        image: registry.digitalocean.com/meschac38000/fastapi-starter:latest
        imagePullPolicy: Always
        command: [ "sh", "-c", "/home/appuser/app/www/scripts/entrypoint.sh" ]
        ports:
        - name: api-port
          containerPort: 8000
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secret
        livenessProbe: &probe
          httpGet:
            httpHeaders:
              - name: HOST
                value: localhost
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe: *probe
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"

      imagePullSecrets:
        - name: regcred
